table 51315 "Timetable Header"
{
    Caption = 'Timetable Header';
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "Academic Year"; Code[25])
        {
            Caption = 'Academic Year';
            TableRelation = "ACA-Academic Year";
        }
        field(19; "Document No."; Code[20])
        {
            Caption = 'Document No.';
            Editable = false;
        }
        field(2; Semester; Code[25])
        {
            Caption = 'Semester';
            TableRelation = "ACA-Semesters";
        }
        field(3; "Generated By"; Code[50])
        {
            Caption = 'Generated By';
        }
        //Type
        field(4; "Type"; Option)
        {
            Caption = 'Type';
            OptionMembers = Class,Exam;
        }
        field(5; "Programme Filter"; Code[25])
        {
            Caption = 'Programme Filter';
            TableRelation = "ACA-Programme";
            FieldClass = FlowFilter;
        }
        field(6; "Stage Filter"; code[25])
        {
            caption = 'Stage Filter';
            tableRelation = "ACA-Programme Stages".Code;
            fieldClass = FlowFilter;
        }
        field(7; "Lecturer Filter"; code[25])
        {
            Caption = 'Lecturer Filter';
            TableRelation = "HRM-Employee C" where(Lecturer = const(true));
            FieldClass = FlowFilter;
        }
        //Exam Type
        field(8; "Exam Type"; Option)
        {
            Caption = 'Exam Type';
            OptionMembers = Regular,Supplementary,Special;
            OptionCaption = 'Regular,Supplementary,Special';
        }
        //Start Date
        field(9; "Start Date"; Date)
        {
            Caption = 'Start Date';
        }
        //End Date
        field(10; "End Date"; Date)
        {
            Caption = 'End Date';
        }
        //Group Description
        field(11; "Group Description"; Text[100])
        {
            Caption = 'Group Description';
        }
        //Year Filter
        field(12; "Year Filter"; Text[100])
        {
            Caption = 'Year Filter';
        }
        //School Filter
        field(13; "School Filter"; Text[1048])
        {
            Caption = 'School Filter';
        }
        //Exclude Years
        field(14; "Exclude Years"; Boolean)
        {
            Caption = 'Exclude Years';
        }
        //Exclude Schools
        field(15; "Exclude Schools"; Boolean)
        {
            Caption = 'Exclude Schools';
        }
        //Exclude Programmes
        field(16; "Exclude Programmes"; Boolean)
        {
            Caption = 'Exclude Programmes';
        }
        //Entry No
        field(17; "Entry No."; Integer)
        {
            Caption = 'Entry No.';
            AutoIncrement = true;
        }
        //programme filter
        field(18; "Exam Programme Filter"; Text[1048])
        {
            Caption = 'Exam Programme Filter';
        }
        //Timetable Status
        field(20; "Timetable Status"; Option)
        {
            Caption = 'Timetable Status';
            OptionMembers = Draft,Final;
        }
        //Linked Timetable No
        field(21; "Linked Timetable No."; Code[20])
        {
            Caption = 'Linked Timetable No.';
            TableRelation = "Timetable Header"."Document No." where(Semester = field(Semester),"Timetable Status" = const(Draft));
        }
    }
    keys
    {
        key(PK; "Document No.", "Academic Year", Semester, "Type", "Exam Type", "Entry No.")
        {
            Clustered = true;
        }
        key(Key2; "Academic Year", Semester, "Type", "Exam Type", "Entry No.")
        {
        }
    }
    trigger oninsert()
    var
        TimetableSetup: Record "Timetable Setup";
        NoSeriesMgt: Codeunit NoSeriesManagement;
    begin
        "Generated By" := USERID;

        if "Document No." = '' then begin
            TimetableSetup.Get();
            TimetableSetup.TestField("Timetable Document Nos.");
            NoSeriesMgt.InitSeries(TimetableSetup."Timetable Document Nos.", xRec."Document No.", 0D, "Document No.", TimetableSetup."Timetable Document Nos.");
        end;
    end;

    trigger OnModify()
    begin
        "Generated By" := USERID;
    end;
}
