page 52086 "Timetable Header List"
{
    ApplicationArea = All;
    Caption = 'Timetable Header List';
    PageType = List;
    SourceTable = "Timetable Header";
    CardPageId="Timetable Header";

    layout
    {
        area(Content)
        {
            repeater(General)
            {
                field("Academic Year"; Rec."Academic Year")
                {
                    ToolTip = 'Specifies the value of the Academic Year field.', Comment = '%';
                }
                field(Semester; Rec.Semester)
                {
                    ToolTip = 'Specifies the value of the Semester field.', Comment = '%';
                }
                field("Generated By"; Rec."Generated By")
                {
                    ToolTip = 'Specifies the value of the Generated By field.', Comment = '%';
                }
            }
        }
    }
}
